name: Eggplant Runner Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Run-Test-Configuration:
    runs-on: self-hosted
    name: Run Test Configuration
    steps:
      - name: Eggplant Runner 1
        uses: keysight-eggplant/eggplant-github-action@v1.0.7
        with:
          dryRun: false
          serverURL: "http://5cd151jqn2:8000/"
          clientID: "client:dai:api:integration:bbf56fa9-8511-4f21-9344-24dce63aec2a"
          testConfigID: "bf4d520f-11a0-41a1-98dc-71c9c1058db1" # Test configuration which need to perform execution
          clientSecret: "tKHUXG4TzfJqAx1j2dTlVyyteMSAd61d" # Eggplant DAI service client secret
          eggplantRunnerPath: "C:/GithubActions/actions-runner/eggplant-runner-Windows-7.0.0-3.exe" 
          # Alternatively, DAI client secret can be set as repo secret
          # byy goingg to GitHub Settings > Secrets > Actions
          # clientSecret: "${{secrets.DAI_CLIENT_SECRET}}
      - name: Eggplant Runner 2
        uses: keysight-eggplant/eggplant-github-action@v1.0.7
        with:
          dryRun: false
          serverURL: "http://5cd151jqn2:8000/"
          clientID: "client:dai:api:integration:bbf56fa9-8511-4f21-9344-24dce63aec2a"
          testConfigID: "bf4d520f-11a0-41a1-98dc-71c9c1058db1" # Test configuration which need to perform execution
          clientSecret: "tKHUXG4TzfJqAx1j2dTlVyyteMSAd61d" # Eggplant DAI service client secret
          eggplantRunnerPath: "C:/GithubActions/actions-runner/eggplant-runner-Windows-7.0.0-3.exe" 
          # Alternatively, DAI client secret can be set as repo secret
          # byy goingg to GitHub Settings > Secrets > Actions
          # clientSecret: "${{secrets.DAI_CLIENT_SECRET}}"

