name: Eggplant Runner Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Run-Test-Configuration:
    runs-on: self-hosted
    name: Run Test Configuration
    steps:
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.8
        with:
          dryRun: false
          serverURL: "http://5cd151jqn2:8000"
          clientID: "client:dai:api:integration:ad023af6-4c0b-491d-9629-5c13d6524b38"
          testConfigID: "7bff1889-a576-4eff-99fd-cefb2059ec8f" # Test configuration which need to perform execution
          clientSecret: "68HEQmJrU99OZhr7ZLU0zLbhhi2FMIEG" # Eggplant DAI service client secret
          # Alternatively, DAI client secret can be set as repo secret
          # by going to GitHub Settings > Secrets > Actions
          # clientSecret: "${{secrets.DAI_CLIENT_SECRET}}"
